//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.AreaApplication = new HashSet<AreaApplication>();
            this.EquipmentApplication = new HashSet<EquipmentApplication>();
        }
    
        public int ID { get; set; }
        public string ApartmentArea { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<AreaApplication> AreaApplication { get; set; }
        public virtual ICollection<EquipmentApplication> EquipmentApplication { get; set; }
    }
}
