//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnest.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartnestEntities : DbContext
    {
        public SmartnestEntities()
            : base("name=SmartnestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Application> Application { get; set; }
        public DbSet<Area> Area { get; set; }
        public DbSet<AreaApplication> AreaApplication { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<EquipmentApplication> EquipmentApplication { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<UserApplication> UserApplication { get; set; }
    }
}
