//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smartnest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserApplication
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ApplicationID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual User User { get; set; }
    }
}
